### ISSUE TITLE
rattler should ignore missing `arch` repodata.json

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#172]
Only `noarch` should always be required -- a missing `win-64`, or `linux-64` etc. folder should be ignored.

**Comment by baszalmstra** [comment]
@wolfv and I discussed this on Discord. The issue is that if you specify a channel like `emscripten-forge` the code will by default try to find `repodata.json` in the `win-64` (on windows) and `noarch` subdirs. However, there is no `win-64` subdir for that channel. Only for `noarch`. This currently results in an error because the `win-64` `repodata.json` could not be found.

The idea is that if the server returns a `404` for an arch specific subdir that we can safely ignore that.

**Comment by carschandler** [comment]
I think I may still be experiencing this error. I have a simple channel:
```
 conda_channel
└──  noarch
    ├──  current_repodata.json
    ├──  index.html
    ├──  proj_area-0.0.3-pyh4616a5c_0.conda
    ├──  repodata.json
    └──  repodata_from_packages.json
```
and get
```
ERROR rattler_repodata_gateway::fetch: error=repodata not found
```
upon installing from the channel.

**Comment by wolfv** [comment]
Yeah it says `ERROR` but you can actually ignore it. We should fix the warning though. We are also working on a new repodata gateway that will dramatically improve things :)
