### ISSUE TITLE
`extracted_package_dir` in conda-meta has mix of backward and forward slashes on Windows

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#233]

**Comment by aganders3** [comment]
I looked into this a bit and I can see a couple ways it might be fixed.

Is the only issue the forward slash in `rattler/cache`, or do you see other instances? If so, a small patch to where this (default) cache path is assembled would work, for example:

```diff
diff --git a/crates/rattler/src/lib.rs b/crates/rattler/src/lib.rs
index e437713..9ba33f8 100644
--- a/crates/rattler/src/lib.rs
+++ b/crates/rattler/src/lib.rs
@@ -38,5 +38,5 @@ pub(crate) fn get_test_data_dir() -> PathBuf {
 pub fn default_cache_dir() -> anyhow::Result<PathBuf> {
     Ok(dirs::cache_dir()
         .ok_or_else(|| anyhow::anyhow!("could not determine cache directory for current platform"))?
-        .join("rattler/cache"))
+        .join(PathBuf::from("rattler/cache")))
 }
```
Otherwise std has [`fs::canonicalize()`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) which works, but it converts the whole path to a bit of a different format. Something like this:

```diff
diff --git a/crates/rattler-bin/src/commands/create.rs b/crates/rattler-bin/src/commands/create.rs
index 5162477..95b30a8 100644
--- a/crates/rattler-bin/src/commands/create.rs
+++ b/crates/rattler-bin/src/commands/create.rs
@@ -464,6 +464,8 @@ async fn install_package_to_environment(
     )
     .await?;
 
+    let package_dir = package_dir.canonicalize()?;
+
     // Construct a PrefixRecord for the package
     let prefix_record = PrefixRecord {
         repodata_record,
```

**Comment by baszalmstra** [comment]
I think the solution would be to:

* Canonicalize the `target_dir` (after creating it) in the `rattler::link_package` function.
* Use the [`dunce`](https://crates.io/crates/dunce) crate for normalization instead of [`fs::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) because on Windows `fs::canonicalize` returns a UNC path which most software doesn't expect.

**Comment by baszalmstra** [comment]
If someone implements this it would also be nice to have a test that shows that this actually works. :)

**Comment by aganders3** [comment]
Yes, I agree dunce is the way to go but was unsure of adding dependencies. It's quite small but also could be limited to Windows builds.

If added to `rattler::link_package` it will need to return the updated path. Right now that returns a Vec of paths that get linked, but not the `package_dir`.

Another option to consider is to put this logic in the serializer for `rattler_conda_types::PrefixRecord`.

**Comment by baszalmstra** [comment]
Ah right! I read the issue wrong, I thought the paths were absolute but they are relative.

I think adding it to `create.rs` file is indeed the best place.

**Comment by baszalmstra** [comment]
I think this has recently been fixed. Please reopen if this is still an issue.
