### ISSUE TITLE
`repodata not found` error on valid channel containing only `noarch` subdir

### ISSUE THREAD

**Issue by carschandler** [mamba-org/rattler#647]
Related to #172, opening a new issue per the team's request.

I have a simple channel:
```
 conda_channel
└──  noarch
    ├──  current_repodata.json
    ├──  index.html
    ├──  proj_area-0.0.3-pyh4616a5c_0.conda
    ├──  repodata.json
    └──  repodata_from_packages.json
```

and get

```
ERROR rattler_repodata_gateway::fetch: error=repodata not found
```

upon installing from the channel. Expected behavior depends on what we define as a valid channel. I would say that a valid channel is one that allows you to install all the packages inside it as expected. I'd prefer to just see no errors in this case, especially since the error shows up any time the channel is interacted with (i.e. `pixi project channel add`, `pixi add`, `pixi search`, etc.)

**Comment by carschandler** [comment]
FWIW, `conda` yields no errors or warnings when using this channel. `micromamba` gives me
```
file:////fs2/OpticsLab/Personal/Chandler_Cars/co.. Checked  0.0s
file:////fs2/OpticsLab/Personal/Chandler_Cars/co.. Checked  0.0s
file:////fs2/OpticsLab/Personal/Chandler_Cars/co..  ??.?MB @  ??.?MB/s 0 failed  0.0s
file:////fs2/OpticsLab/Personal/Chandler_Cars/co.. 989.0 B @  10.1kB/s  0.1s
conda-forge/noarch                                  14.5MB @   4.6MB/s  3.1s
conda-forge/win-64                                  22.0MB @   5.3MB/s  4.1s
```
and then proceeds as normal.

**Comment by baszalmstra** [comment]
Are you using `py-rattler`? Or how are you getting this error?

This happens because internally it calls `fetch_repodata` which assumes that the channel subdirectory exists. The function returns a special `NotFound` error (which is also reported to the logs), but the error should just be ignored if the subdir is _not_ noarch.

Once https://github.com/mamba-org/rattler/pull/560/files is merged you will have a much much nicer interface.

**Comment by baszalmstra** [comment]
The gateway feature has landed in rattler, will most likely make its way to pixi and rattler-build soon, closing this for now.
